amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "car_base"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "scan"
    laser_model_type: "likelihood_field"
    max_particles: 2000
    min_particles: 500
    set_initial_pose: true
    initial_pose: {x: 0.0, y: 0.0, yaw: 0.0}

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/ros2_ws/scan_map/maps/lidar_map.yaml"