slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: car_base
    scan_topic: /scan
    mode: mapping
    map_update_interval: 1.0
    resolution: 0.005
    # Force Reliable QoS matching Isaac Sim
    # scan_queue_size: 10
    # qos_reliability_policy: reliable